Kp 5580 asr tests
CSCfi/Kielipankki-palvelut pull request #64
Opened 2023-10-27 08:13 UTC by mmatthiesencsc

Adding this code should not hurt, but the whole process of updating aalto-asr is not well defined.

2023-10-27 13:34 UTC, aajarven requested changes
This PR seems to be of a good vintage. At least the login node has changed since, and I'm not too confident that that is the only thing. Perhaps we should do `git rebase origin/main`, resolve conflicts (if needed) and verify that this playbook works before merging?

2023-10-27 13:34 UTC, aajarven commented on commandline/roles/aalto-asr/README.md
> +`ssh puhti-login2.csc.fi`
The current test inventory uses node 12, so these are outdated

2023-11-01 14:02 UTC, mmatthiesencsc commented
Hi Anni, thanks for making me think twice! This is now tested and working. I did not re-install again, but I did successfully run  ansible-playbook site.yml -vv -i inventories/test_csc -t aalto-asr. There was indeed a bit more to make it work than I originally thought.

2023-11-02 08:28 UTC, aajarven approved these changes
Looking good!

2023-11-02 08:37 UTC, merged